const mongoose = require('mongoose');
const { State, District } = require('../models/index');
const winston = require('winston');

// Logger setup
const logger = winston.createLogger({
  transports: [new winston.transports.File({ filename: 'logs/error.log', level: 'error' })],
});

const statesData = [
    {
      "name": "Andhra Pradesh",
      "code": "AP"
    },
    {
      "name": "Arunachal Pradesh",
      "code": "AR"
    },
    {
      "name": "Assam",
      "code": "AS"
    },
    {
      "name": "Bihar",
      "code": "BR"
    },
    {
      "name": "Chhattisgarh",
      "code": "CG"
    },
    {
      "name": "Goa",
      "code": "GA"
    },
    {
      "name": "Gujarat",
      "code": "GJ"
    },
    {
      "name": "Haryana",
      "code": "HR"
    },
    {
      "name": "Himachal Pradesh",
      "code": "HP"
    },
    {
      "name": "Jharkhand",
      "code": "JH"
    },
    {
      "name": "Karnataka",
      "code": "KA"
    },
    {
      "name": "Kerala",
      "code": "KL"
    },
    {
      "name": "Madhya Pradesh",
      "code": "MP"
    },
    {
      "name": "Maharashtra",
      "code": "MH"
    },
    {
      "name": "Manipur",
      "code": "MN"
    },
    {
      "name": "Meghalaya",
      "code": "ML"
    },
    {
      "name": "Mizoram",
      "code": "MZ"
    },
    {
      "name": "Nagaland",
      "code": "NL"
    },
    {
      "name": "Odisha",
      "code": "OD"
    },
    {
      "name": "Punjab",
      "code": "PB"
    },
    {
      "name": "Rajasthan",
      "code": "RJ"
    },
    {
      "name": "Sikkim",
      "code": "SK"
    },
    {
      "name": "Tamil Nadu",
      "code": "TN"
    },
    {
      "name": "Telangana",
      "code": "TG"
    },
    {
      "name": "Tripura",
      "code": "TR"
    },
    {
      "name": "Uttar Pradesh",
      "code": "UP"
    },
    {
      "name": "Uttarakhand",
      "code": "UK"
    },
    {
      "name": "West Bengal",
      "code": "WB"
    },
    {
      "name": "Andaman and Nicobar Islands",
      "code": "AN"
    },
    {
      "name": "Chandigarh",
      "code": "CH"
    },
    {
      "name": "Dadra and Nagar Haveli and Daman and Diu",
      "code": "DN"
    },
    {
      "name": "Delhi",
      "code": "DL"
    },
    {
      "name": "Jammu and Kashmir",
      "code": "JK"
    },
    {
      "name": "Ladakh",
      "code": "LA"
    },
    {
      "name": "Lakshadweep",
      "code": "LD"
    },
    {
      "name": "Puducherry",
      "code": "PY"
    }
  ]


const districtsData = [
    { "name": "Anantapur", "stateId": "AP", "code": "AP-ANT" },
    { "name": "Chittoor", "stateId": "AP", "code": "AP-CHT" },
    { "name": "East Godavari", "stateId": "AP", "code": "AP-EGD" },
    { "name": "Guntur", "stateId": "AP", "code": "AP-GNT" },
    { "name": "Krishna", "stateId": "AP", "code": "AP-KRI" },
    { "name": "Kurnool", "stateId": "AP", "code": "AP-KUR" },
    { "name": "Prakasam", "stateId": "AP", "code": "AP-PRA" },
    { "name": "Srikakulam", "stateId": "AP", "code": "AP-SRI" },
    { "name": "Sri Potti Sriramulu Nellore", "stateId": "AP", "code": "AP-NEL" },
    { "name": "Visakhapatnam", "stateId": "AP", "code": "AP-VSK" },
    { "name": "Vizianagaram", "stateId": "AP", "code": "AP-VZM" },
    { "name": "West Godavari", "stateId": "AP", "code": "AP-WGD" },
    { "name": "YSR District, Kadapa", "stateId": "AP", "code": "AP-KDP" },
    { "name": "Alluri Sitharama Raju", "stateId": "AP", "code": "AP-ASR" },
    { "name": "Anakapalli", "stateId": "AP", "code": "AP-ANK" },
    { "name": "Bapatla", "stateId": "AP", "code": "AP-BAP" },
    { "name": "Eluru", "stateId": "AP", "code": "AP-ELR" },
    { "name": "Kakinada", "stateId": "AP", "code": "AP-KKD" },
    { "name": "Konaseema", "stateId": "AP", "code": "AP-KNS" },
    { "name": "Manyam", "stateId": "AP", "code": "AP-MNY" },
    { "name": "NTR", "stateId": "AP", "code": "AP-NTR" },
    { "name": "Nandyal", "stateId": "AP", "code": "AP-NDL" },
    { "name": "Palnadu", "stateId": "AP", "code": "AP-PLN" },
    { "name": "Sri Sathya Sai", "stateId": "AP", "code": "AP-SSS" },
    { "name": "Tirupati", "stateId": "AP", "code": "AP-TPT" },
    { "name": "Sri Balaji", "stateId": "AP", "code": "AP-SBJ" },
    { "name": "Anjaw", "stateId": "AR", "code": "AR-ANJ" },
    { "name": "Changlang", "stateId": "AR", "code": "AR-CHA" },
    { "name": "Dibang Valley", "stateId": "AR", "code": "AR-DIB" },
    { "name": "East Kameng", "stateId": "AR", "code": "AR-EKA" },
    { "name": "East Siang", "stateId": "AR", "code": "AR-ESI" },
    { "name": "Kamle", "stateId": "AR", "code": "AR-KAM" },
    { "name": "Kra Daadi", "stateId": "AR", "code": "AR-KRD" },
    { "name": "Kurung Kumey", "stateId": "AR", "code": "AR-KUK" },
    { "name": "Lepa Rada", "stateId": "AR", "code": "AR-LER" },
    { "name": "Lohit", "stateId": "AR", "code": "AR-LOH" },
    { "name": "Longding", "stateId": "AR", "code": "AR-LDG" },
    { "name": "Lower Dibang Valley", "stateId": "AR", "code": "AR-LDV" },
    { "name": "Lower Siang", "stateId": "AR", "code": "AR-LSI" },
    { "name": "Lower Subansiri", "stateId": "AR", "code": "AR-LSU" },
    { "name": "Namsai", "stateId": "AR", "code": "AR-NAM" },
    { "name": "Pakke Kessang", "stateId": "AR", "code": "AR-PKK" },
    { "name": "Papum Pare", "stateId": "AR", "code": "AR-PAP" },
    { "name": "Shi Yomi", "stateId": "AR", "code": "AR-SHY" },
    { "name": "Siang", "stateId": "AR", "code": "AR-SIA" },
    { "name": "Tawang", "stateId": "AR", "code": "AR-TAW" },
    { "name": "Tirap", "stateId": "AR", "code": "AR-TIR" },
    { "name": "Upper Siang", "stateId": "AR", "code": "AR-USI" },
    { "name": "Upper Subansiri", "stateId": "AR", "code": "AR-USU" },
    { "name": "West Kameng", "stateId": "AR", "code": "AR-WKA" },
    { "name": "West Siang", "stateId": "AR", "code": "AR-WSI" },
    { "name": "Itanagar Capital Complex", "stateId": "AR", "code": "AR-ICC" },
    { "name": "Baksa", "stateId": "AS", "code": "AS-BAK" },
    { "name": "Barpeta", "stateId": "AS", "code": "AS-BAR" },
    { "name": "Biswanath", "stateId": "AS", "code": "AS-BIS" },
    { "name": "Bongaigaon", "stateId": "AS", "code": "AS-BON" },
    { "name": "Cachar", "stateId": "AS", "code": "AS-CAC" },
    { "name": "Charaideo", "stateId": "AS", "code": "AS-CHA" },
    { "name": "Chirang", "stateId": "AS", "code": "AS-CHI" },
    { "name": "Darrang", "stateId": "AS", "code": "AS-DAR" },
    { "name": "Dhemaji", "stateId": "AS", "code": "AS-DHE" },
    { "name": "Dhubri", "stateId": "AS", "code": "AS-DHU" },
    { "name": "Dibrugarh", "stateId": "AS", "code": "AS-DIB" },
    { "name": "Dima Hasao", "stateId": "AS", "code": "AS-DIM" },
    { "name": "Goalpara", "stateId": "AS", "code": "AS-GOA" },
    { "name": "Golaghat", "stateId": "AS", "code": "AS-GOL" },
    { "name": "Hailakandi", "stateId": "AS", "code": "AS-HAI" },
    { "name": "Hojai", "stateId": "AS", "code": "AS-HOJ" },
    { "name": "Jorhat", "stateId": "AS", "code": "AS-JOR" },
    { "name": "Kamrup", "stateId": "AS", "code": "AS-KAM" },
    { "name": "Kamrup Metropolitan", "stateId": "AS", "code": "AS-KMM" },
    { "name": "Karbi Anglong", "stateId": "AS", "code": "AS-KAR" },
    { "name": "Karimganj", "stateId": "AS", "code": "AS-KAG" },
    { "name": "Kokrajhar", "stateId": "AS", "code": "AS-KOK" },
    { "name": "Lakhimpur", "stateId": "AS", "code": "AS-LAK" },
    { "name": "Majuli", "stateId": "AS", "code": "AS-MAJ" },
    { "name": "Morigaon", "stateId": "AS", "code": "AS-MOR" },
    { "name": "Nagaon", "stateId": "AS", "code": "AS-NAG" },
    { "name": "Nalbari", "stateId": "AS", "code": "AS-NAL" },
    { "name": "Sivasagar", "stateId": "AS", "code": "AS-SIV" },
    { "name": "Sonitpur", "stateId": "AS", "code": "AS-SON" },
    { "name": "South Salmara-Mankachar", "stateId": "AS", "code": "AS-SSM" },
    { "name": "Tinsukia", "stateId": "AS", "code": "AS-TIN" },
    { "name": "Udalguri", "stateId": "AS", "code": "AS-UDA" },
    { "name": "West Karbi Anglong", "stateId": "AS", "code": "AS-WKA" },
    { "name": "Bajali", "stateId": "AS", "code": "AS-BAJ" },
    { "name": "Tamulpur", "stateId": "AS", "code": "AS-TAM" },
    { "name": "Araria", "stateId": "BR", "code": "BR-ARA" },
    { "name": "Arwal", "stateId": "BR", "code": "BR-ARW" },
    { "name": "Aurangabad", "stateId": "BR", "code": "BR-AUR" },
    { "name": "Banka", "stateId": "BR", "code": "BR-BNK" },
    { "name": "Begusarai", "stateId": "BR", "code": "BR-BEG" },
    { "name": "Bhagalpur", "stateId": "BR", "code": "BR-BHA" },
    { "name": "Bhojpur", "stateId": "BR", "code": "BR-BHO" },
    { "name": "Buxar", "stateId": "BR", "code": "BR-BUX" },
    { "name": "Darbhanga", "stateId": "BR", "code": "BR-DAR" },
    { "name": "East Champaran", "stateId": "BR", "code": "BR-ECH" },
    { "name": "Gaya", "stateId": "BR", "code": "BR-GAY" },
    { "name": "Gopalganj", "stateId": "BR", "code": "BR-GOP" },
    { "name": "Jamui", "stateId": "BR", "code": "BR-JAM" },
    { "name": "Jehanabad", "stateId": "BR", "code": "BR-JEH" },
    { "name": "Kaimur", "stateId": "BR", "code": "BR-KAI" },
    { "name": "Katihar", "stateId": "BR", "code": "BR-KAT" },
    { "name": "Khagaria", "stateId": "BR", "code": "BR-KHA" },
    { "name": "Kishanganj", "stateId": "BR", "code": "BR-KIS" },
    { "name": "Lakhisarai", "stateId": "BR", "code": "BR-LAK" },
    { "name": "Madhepura", "stateId": "BR", "code": "BR-MAD" },
    { "name": "Madhubani", "stateId": "BR", "code": "BR-MDB" },
    { "name": "Munger", "stateId": "BR", "code": "BR-MUN" },
    { "name": "Muzaffarpur", "stateId": "BR", "code": "BR-MUZ" },
    { "name": "Nalanda", "stateId": "BR", "code": "BR-NAL" },
    { "name": "Nawada", "stateId": "BR", "code": "BR-NAW" },
    { "name": "Patna", "stateId": "BR", "code": "BR-PAT" },
    { "name": "Purnia", "stateId": "BR", "code": "BR-PUR" },
    { "name": "Rohtas", "stateId": "BR", "code": "BR-ROH" },
    { "name": "Saharsa", "stateId": "BR", "code": "BR-SAH" },
    { "name": "Samastipur", "stateId": "BR", "code": "BR-SAM" },
    { "name": "Saran", "stateId": "BR", "code": "BR-SAR" },
    { "name": "Sheikhpura", "stateId": "BR", "code": "BR-SHE" },
    { "name": "Sheohar", "stateId": "BR", "code": "BR-SHO" },
    { "name": "Sitamarhi", "stateId": "BR", "code": "BR-SIT" },
    { "name": "Siwan", "stateId": "BR", "code": "BR-SIW" },
    { "name": "Supaul", "stateId": "BR", "code": "BR-SUP" },
    { "name": "Vaishali", "stateId": "BR", "code": "BR-VAI" },
    { "name": "West Champaran", "stateId": "BR", "code": "BR-WCH" },
    { "name": "Balod", "stateId": "CG", "code": "CG-BAL" },
    { "name": "Baloda Bazar", "stateId": "CG", "code": "CG-BAB" },
    { "name": "Balrampur", "stateId": "CG", "code": "CG-BRM" },
    { "name": "Bastar", "stateId": "CG", "code": "CG-BAS" },
    { "name": "Bemetara", "stateId": "CG", "code": "CG-BEM" },
    { "name": "Bijapur", "stateId": "CG", "code": "CG-BIJ" },
    { "name": "Bilaspur", "stateId": "CG", "code": "CG-BIL" },
    { "name": "Dantewada", "stateId": "CG", "code": "CG-DAN" },
    { "name": "Dhamtari", "stateId": "CG", "code": "CG-DHM" },
    { "name": "Durg", "stateId": "CG", "code": "CG-DUR" },
    { "name": "Gariaband", "stateId": "CG", "code": "CG-GAR" },
    { "name": "Janjgir-Champa", "stateId": "CG", "code": "CG-JAN" },
    { "name": "Jashpur", "stateId": "CG", "code": "CG-JAS" },
    { "name": "Kabirdham", "stateId": "CG", "code": "CG-KAB" },
    { "name": "Kanker", "stateId": "CG", "code": "CG-KAN" },
    { "name": "Kondagaon", "stateId": "CG", "code": "CG-KON" },
    { "name": "Korba", "stateId": "CG", "code": "CG-KOR" },
    { "name": "Koriya", "stateId": "CG", "code": "CG-KRY" },
    { "name": "Mahasamund", "stateId": "CG", "code": "CG-MAH" },
    { "name": "Mungeli", "stateId": "CG", "code": "CG-MUN" },
    { "name": "Narayanpur", "stateId": "CG", "code": "CG-NAR" },
    { "name": "Raigarh", "stateId": "CG", "code": "CG-RAI" },
    { "name": "Raipur", "stateId": "CG", "code": "CG-RPR" },
    { "name": "Rajnandgaon", "stateId": "CG", "code": "CG-RAJ" },
    { "name": "Sukma", "stateId": "CG", "code": "CG-SUK" },
    { "name": "Surajpur", "stateId": "CG", "code": "CG-SUR" },
    { "name": "Surguja", "stateId": "CG", "code": "CG-SRG" },
    { "name": "Gaurela-Pendra-Marwahi", "stateId": "CG", "code": "CG-GPM" },
    { "name": "Mohla-Manpur-Ambagarh Chowki", "stateId": "CG", "code": "CG-MMA" },
    { "name": "Sarangarh-Bilaigarh", "stateId": "CG", "code": "CG-SBG" },
    { "name": "Khairagarh-Chhuikhadan-Gandai", "stateId": "CG", "code": "CG-KCG" },
    { "name": "Manendragarh-Chirmiri-Bharatpur", "stateId": "CG", "code": "CG-MCB" },
    { "name": "Sakti", "stateId": "CG", "code": "CG-SAK" },
    { "name": "North Goa", "stateId": "GA", "code": "GA-NGO" },
    { "name": "South Goa", "stateId": "GA", "code": "GA-SGO" },
    { "name": "Ahmedabad", "stateId": "GJ", "code": "GJ-AHM" },
    { "name": "Amreli", "stateId": "GJ", "code": "GJ-AMR" },
    { "name": "Anand", "stateId": "GJ", "code": "GJ-ANA" },
    { "name": "Aravalli", "stateId": "GJ", "code": "GJ-ARV" },
    { "name": "Banaskantha", "stateId": "GJ", "code": "GJ-BAN" },
    { "name": "Bharuch", "stateId": "GJ", "code": "GJ-BHA" },
    { "name": "Bhavnagar", "stateId": "GJ", "code": "GJ-BHV" },
    { "name": "Botad", "stateId": "GJ", "code": "GJ-BOT" },
    { "name": "Chhota Udaipur", "stateId": "GJ", "code": "GJ-CHU" },
    { "name": "Dahod", "stateId": "GJ", "code": "GJ-DAH" },
    { "name": "Dang", "stateId": "GJ", "code": "GJ-DAN" },
    { "name": "Devbhoomi Dwarka", "stateId": "GJ", "code": "GJ-DED" },
    { "name": "Gandhinagar", "stateId": "GJ", "code": "GJ-GAN" },
    { "name": "Gir Somnath", "stateId": "GJ", "code": "GJ-GIR" },
    { "name": "Jamnagar", "stateId": "GJ", "code": "GJ-JAM" },
    { "name": "Junagadh", "stateId": "GJ", "code": "GJ-JUN" },
    { "name": "Kheda", "stateId": "GJ", "code": "GJ-KHE" },
    { "name": "Kutch", "stateId": "GJ", "code": "GJ-KUT" },
    { "name": "Mahisagar", "stateId": "GJ", "code": "GJ-MAH" },
    { "name": "Mehsana", "stateId": "GJ", "code": "GJ-MEH" },
    { "name": "Morbi", "stateId": "GJ", "code": "GJ-MOR" },
    { "name": "Narmada", "stateId": "GJ", "code": "GJ-NAR" },
    { "name": "Navsari", "stateId": "GJ", "code": "GJ-NAV" },
    { "name": "Panchmahal", "stateId": "GJ", "code": "GJ-PAN" },
    { "name": "Patan", "stateId": "GJ", "code": "GJ-PAT" },
    { "name": "Porbandar", "stateId": "GJ", "code": "GJ-POR" },
    { "name": "Rajkot", "stateId": "GJ", "code": "GJ-RAJ" },
    { "name": "Sabarkantha", "stateId": "GJ", "code": "GJ-SAB" },
    { "name": "Surat", "stateId": "GJ", "code": "GJ-SUR" },
    { "name": "Surendranagar", "stateId": "GJ", "code": "GJ-SRN" },
    { "name": "Tapi", "stateId": "GJ", "code": "GJ-TAP" },
    { "name": "Vadodara", "stateId": "GJ", "code": "GJ-VAD" },
    { "name": "Valsad", "stateId": "GJ", "code": "GJ-VAL" },
    { "name": "Dwarka", "stateId": "GJ", "code": "GJ-DWA" },
    { "name": "Ambala", "stateId": "HR", "code": "HR-AMB" },
    { "name": "Bhiwani", "stateId": "HR", "code": "HR-BHI" },
    { "name": "Charkhi Dadri", "stateId": "HR", "code": "HR-CKD" },
    { "name": "Faridabad", "stateId": "HR", "code": "HR-FAR" },
    { "name": "Fatehabad", "stateId": "HR", "code": "HR-FTB" },
    { "name": "Gurugram", "stateId": "HR", "code": "HR-GUR" },
    { "name": "Hisar", "stateId": "HR", "code": "HR-HIS" },
    { "name": "Jhajjar", "stateId": "HR", "code": "HR-JHA" },
    { "name": "Jind", "stateId": "HR", "code": "HR-JIN" },
    { "name": "Kaithal", "stateId": "HR", "code": "HR-KAI" },
    { "name": "Karnal", "stateId": "HR", "code": "HR-KAR" },
    { "name": "Kurukshetra", "stateId": "HR", "code": "HR-KUR" },
    { "name": "Mahendragarh", "stateId": "HR", "code": "HR-MAH" },
    { "name": "Nuh", "stateId": "HR", "code": "HR-NUH" },
    { "name": "Palwal", "stateId": "HR", "code": "HR-PAL" },
    { "name": "Panchkula", "stateId": "HR", "code": "HR-PAN" },
    { "name": "Panipat", "stateId": "HR", "code": "HR-PNP" },
    { "name": "Rewari", "stateId": "HR", "code": "HR-REW" },
    { "name": "Rohtak", "stateId": "HR", "code": "HR-ROH" },
    { "name": "Sirsa", "stateId": "HR", "code": "HR-SIR" },
    { "name": "Sonipat", "stateId": "HR", "code": "HR-SON" },
    { "name": "Yamunanagar", "stateId": "HR", "code": "HR-YAM" },
    { "name": "Bilaspur", "stateId": "HP", "code": "HP-BIL" },
    { "name": "Chamba", "stateId": "HP", "code": "HP-CHA" },
    { "name": "Hamirpur", "stateId": "HP", "code": "HP-HAM" },
    { "name": "Kangra", "stateId": "HP", "code": "HP-KAN" },
    { "name": "Kinnaur", "stateId": "HP", "code": "HP-KIN" },
    { "name": "Kullu", "stateId": "HP", "code": "HP-KUL" },
    { "name": "Lahaul and Spiti", "stateId": "HP", "code": "HP-LAS" },
    { "name": "Mandi", "stateId": "HP", "code": "HP-MAN" },
    { "name": "Shimla", "stateId": "HP", "code": "HP-SHI" },
    { "name": "Sirmaur", "stateId": "HP", "code": "HP-SIR" },
    { "name": "Solan", "stateId": "HP", "code": "HP-SOL" },
    { "name": "Una", "stateId": "HP", "code": "HP-UNA" },
    { "name": "Bokaro", "stateId": "JH", "code": "JH-BOK" },
    { "name": "Chatra", "stateId": "JH", "code": "JH-CHA" },
    { "name": "Deoghar", "stateId": "JH", "code": "JH-DEO" },
    { "name": "Dhanbad", "stateId": "JH", "code": "JH-DHA" },
    { "name": "Dumka", "stateId": "JH", "code": "JH-DUM" },
    { "name": "East Singhbhum", "stateId": "JH", "code": "JH-ESI" },
    { "name": "Garhwa", "stateId": "JH", "code": "JH-GAR" },
    { "name": "Giridih", "stateId": "JH", "code": "JH-GIR" },
    { "name": "Godda", "stateId": "JH", "code": "JH-GOD" },
    { "name": "Gumla", "stateId": "JH", "code": "JH-GUM" },
    { "name": "Hazaribagh", "stateId": "JH", "code": "JH-HAZ" },
    { "name": "Jamtara", "stateId": "JH", "code": "JH-JAM" },
    { "name": "Khunti", "stateId": "JH", "code": "JH-KHU" },
    { "name": "Koderma", "stateId": "JH", "code": "JH-KOD" },
    { "name": "Latehar", "stateId": "JH", "code": "JH-LAT" },
    { "name": "Lohardaga", "stateId": "JH", "code": "JH-LOH" },
    { "name": "Pakur", "stateId": "JH", "code": "JH-PAK" },
    { "name": "Palamu", "stateId": "JH", "code": "JH-PAL" },
    { "name": "Ramgarh", "stateId": "JH", "code": "JH-RAM" },
    { "name": "Ranchi", "stateId": "JH", "code": "JH-RAN" },
    { "name": "Sahibganj", "stateId": "JH", "code": "JH-SAH" },
    { "name": "Seraikela Kharsawan", "stateId": "JH", "code": "JH-SER" },
    { "name": "Simdega", "stateId": "JH", "code": "JH-SIM" },
    { "name": "West Singhbhum", "stateId": "JH", "code": "JH-WSI" },
    { "name": "Bagalkot", "stateId": "KA", "code": "KA-BAG" },
    { "name": "Ballari", "stateId": "KA", "code": "KA-BAL" },
    { "name": "Belagavi", "stateId": "KA", "code": "KA-BEL" },
    { "name": "Bengaluru Rural", "stateId": "KA", "code": "KA-BGR" },
    { "name": "Bengaluru Urban", "stateId": "KA", "code": "KA-BGU" },
    { "name": "Bidar", "stateId": "KA", "code": "KA-BID" },
    { "name": "Chamarajanagar", "stateId": "KA", "code": "KA-CHA" },
    { "name": "Chikballapur", "stateId": "KA", "code": "KA-CHI" },
    { "name": "Chikkamagaluru", "stateId": "KA", "code": "KA-CHM" },
    { "name": "Chitradurga", "stateId": "KA", "code": "KA-CHT" },
    { "name": "Dakshina Kannada", "stateId": "KA", "code": "KA-DAK" },
    { "name": "Davanagere", "stateId": "KA", "code": "KA-DAV" },
    { "name": "Dharwad", "stateId": "KA", "code": "KA-DHA" },
    { "name": "Gadag", "stateId": "KA", "code": "KA-GAD" },
    { "name": "Hassan", "stateId": "KA", "code": "KA-HAS" },
    { "name": "Haveri", "stateId": "KA", "code": "KA-HAV" },
    { "name": "Kalaburagi", "stateId": "KA", "code": "KA-KAL" },
    { "name": "Kodagu", "stateId": "KA", "code": "KA-KOD" },
    { "name": "Kolar", "stateId": "KA", "code": "KA-KOL" },
    { "name": "Koppal", "stateId": "KA", "code": "KA-KOP" },
    { "name": "Mandya", "stateId": "KA", "code": "KA-MAN" },
    { "name": "Mysuru", "stateId": "KA", "code": "KA-MYS" },
    { "name": "Raichur", "stateId": "KA", "code": "KA-RAI" },
    { "name": "Ramanagara", "stateId": "KA", "code": "KA-RAM" },
    { "name": "Shivamogga", "stateId": "KA", "code": "KA-SHI" },
    { "name": "Tumakuru", "stateId": "KA", "code": "KA-TUM" },
    { "name": "Udupi", "stateId": "KA", "code": "KA-UDU" },
    { "name": "Uttara Kannada", "stateId": "KA", "code": "KA-UTK" },
    { "name": "Vijayapura", "stateId": "KA", "code": "KA-VIJ" },
    { "name": "Yadgir", "stateId": "KA", "code": "KA-YAD" },
    { "name": "Vijayanagara", "stateId": "KA", "code": "KA-VJN" },
    { "name": "Alappuzha", "stateId": "KL", "code": "KL-ALA" },
    { "name": "Ernakulam", "stateId": "KL", "code": "KL-ERN" },
    { "name": "Idukki", "stateId": "KL", "code": "KL-IDU" },
    { "name": "Kannur", "stateId": "KL", "code": "KL-KAN" },
    { "name": "Kasaragod", "stateId": "KL", "code": "KL-KAS" },
    { "name": "Kollam", "stateId": "KL", "code": "KL-KOL" },
    { "name": "Kottayam", "stateId": "KL", "code": "KL-KOT" },
    { "name": "Kozhikode", "stateId": "KL", "code": "KL-KOZ" },
    { "name": "Malappuram", "stateId": "KL", "code": "KL-MAL" },
    { "name": "Palakkad", "stateId": "KL", "code": "KL-PAL" },
    { "name": "Pathanamthitta", "stateId": "KL", "code": "KL-PAT" },
    { "name": "Thiruvananthapuram", "stateId": "KL", "code": "KL-THI" },
    { "name": "Thrissur", "stateId": "KL", "code": "KL-THR" },
    { "name": "Wayanad", "stateId": "KL", "code": "KL-WAY" },
    { "name": "Agar Malwa", "stateId": "MP", "code": "MP-AGM" },
    { "name": "Alirajpur", "stateId": "MP", "code": "MP-ALI" },
    { "name": "Anuppur", "stateId": "MP", "code": "MP-ANU" },
    { "name": "Ashoknagar", "stateId": "MP", "code": "MP-ASH" },
    { "name": "Balaghat", "stateId": "MP", "code": "MP-BAL" },
    { "name": "Barwani", "stateId": "MP", "code": "MP-BAR" },
    { "name": "Betul", "stateId": "MP", "code": "MP-BET" },
    { "name": "Bhind", "stateId": "MP", "code": "MP-BHI" },
    { "name": "Bhopal", "stateId": "MP", "code": "MP-BHO" },
    { "name": "Burhanpur", "stateId": "MP", "code": "MP-BUR" },
    { "name": "Chhatarpur", "stateId": "MP", "code": "MP-CHH" },
    { "name": "Chhindwara", "stateId": "MP", "code": "MP-CHI" },
    { "name": "Damoh", "stateId": "MP", "code": "MP-DAM" },
    { "name": "Datia", "stateId": "MP", "code": "MP-DAT" },
    { "name": "Dewas", "stateId": "MP", "code": "MP-DEW" },
    { "name": "Dhar", "stateId": "MP", "code": "MP-DHA" },
    { "name": "Dindori", "stateId": "MP", "code": "MP-DIN" },
    { "name": "Guna", "stateId": "MP", "code": "MP-GUN" },
    { "name": "Gwalior", "stateId": "MP", "code": "MP-GWA" },
    { "name": "Harda", "stateId": "MP", "code": "MP-HAR" },
    { "name": "Hoshangabad", "stateId": "MP", "code": "MP-HOS" },
    { "name": "Indore", "stateId": "MP", "code": "MP-IND" },
    { "name": "Jabalpur", "stateId": "MP", "code": "MP-JAB" },
    { "name": "Jhabua", "stateId": "MP", "code": "MP-JHA" },
    { "name": "Katni", "stateId": "MP", "code": "MP-KAT" },
    { "name": "Khandwa", "stateId": "MP", "code": "MP-KHA" },
    { "name": "Khargone", "stateId": "MP", "code": "MP-KHG" },
    { "name": "Mandla", "stateId": "MP", "code": "MP-MAN" },
    { "name": "Mandsaur", "stateId": "MP", "code": "MP-MDS" },
    { "name": "Morena", "stateId": "MP", "code": "MP-MOR" },
    { "name": "Narsinghpur", "stateId": "MP", "code": "MP-NAR" },
    { "name": "Neemuch", "stateId": "MP", "code": "MP-NEE" },
    { "name": "Panna", "stateId": "MP", "code": "MP-PAN" },
    { "name": "Raisen", "stateId": "MP", "code": "MP-RAI" },
    { "name": "Rajgarh", "stateId": "MP", "code": "MP-RAJ" },
    { "name": "Ratlam", "stateId": "MP", "code": "MP-RAT" },
    { "name": "Rewa", "stateId": "MP", "code": "MP-REW" },
    { "name": "Sagar", "stateId": "MP", "code": "MP-SAG" },
    { "name": "Satna", "stateId": "MP", "code": "MP-SAT" },
    { "name": "Sehore", "stateId": "MP", "code": "MP-SEH" },
    { "name": "Seoni", "stateId": "MP", "code": "MP-SEO" },
    { "name": "Shahdol", "stateId": "MP", "code": "MP-SHA" },
    { "name": "Shajapur", "stateId": "MP", "code": "MP-SHJ" },
    { "name": "Sheopur", "stateId": "MP", "code": "MP-SHP" },
    { "name": "Shivpuri", "stateId": "MP", "code": "MP-SHI" },
    { "name": "Sidhi", "stateId": "MP", "code": "MP-SID" },
    { "name": "Singrauli", "stateId": "MP", "code": "MP-SIN" },
    { "name": "Tikamgarh", "stateId": "MP", "code": "MP-TIK" },
    { "name": "Ujjain", "stateId": "MP", "code": "MP-UJJ" },
    { "name": "Umaria", "stateId": "MP", "code": "MP-UMA" },
    { "name": "Vidisha", "stateId": "MP", "code": "MP-VID" },
    { "name": "Niwari", "stateId": "MP", "code": "MP-NIW" },
    { "name": "Ahmednagar", "stateId": "MH", "code": "MH-AHM" },
    { "name": "Akola", "stateId": "MH", "code": "MH-AKO" },
    { "name": "Amravati", "stateId": "MH", "code": "MH-AMR" },
    { "name": "Aurangabad", "stateId": "MH", "code": "MH-AUR" },
    { "name": "Beed", "stateId": "MH", "code": "MH-BEE" },
    { "name": "Bhandara", "stateId": "MH", "code": "MH-BHA" },
    { "name": "Buldhana", "stateId": "MH", "code": "MH-BUL" },
    { "name": "Chandrapur", "stateId": "MH", "code": "MH-CHA" },
    { "name": "Dhule", "stateId": "MH", "code": "MH-DHU" },
    { "name": "Gadchiroli", "stateId": "MH", "code": "MH-GAD" },
    { "name": "Gondia", "stateId": "MH", "code": "MH-GON" },
    { "name": "Hingoli", "stateId": "MH", "code": "MH-HIN" },
    { "name": "Jalgaon", "stateId": "MH", "code": "MH-JAL" },
    { "name": "Jalna", "stateId": "MH", "code": "MH-JLN" },
    { "name": "Kolhapur", "stateId": "MH", "code": "MH-KOL" },
    { "name": "Latur", "stateId": "MH", "code": "MH-LAT" },
    { "name": "Mumbai City", "stateId": "MH", "code": "MH-MUM" },
    { "name": "Mumbai Suburban", "stateId": "MH", "code": "MH-MUS" },
    { "name": "Nagpur", "stateId": "MH", "code": "MH-NAG" },
    { "name": "Nanded", "stateId": "MH", "code": "MH-NAN" },
    { "name": "Nandurbar", "stateId": "MH", "code": "MH-NDB" },
    { "name": "Nashik", "stateId": "MH", "code": "MH-NAS" },
    { "name": "Osmanabad", "stateId": "MH", "code": "MH-OSM" },
    { "name": "Palghar", "stateId": "MH", "code": "MH-PAL" },
    { "name": "Parbhani", "stateId": "MH", "code": "MH-PAR" },
    { "name": "Pune", "stateId": "MH", "code": "MH-PUN" },
    { "name": "Raigad", "stateId": "MH", "code": "MH-RAI" },
    { "name": "Ratnagiri", "stateId": "MH", "code": "MH-RAT" },
    { "name": "Sangli", "stateId": "MH", "code": "MH-SAN" },
    { "name": "Satara", "stateId": "MH", "code": "MH-SAT" },
    { "name": "Sindhudurg", "stateId": "MH", "code": "MH-SIN" },
    { "name": "Solapur", "stateId": "MH", "code": "MH-SOL" },
    { "name": "Thane", "stateId": "MH", "code": "MH-THA" },
    { "name": "Wardha", "stateId": "MH", "code": "MH-WAR" },
    { "name": "Washim", "stateId": "MH", "code": "MH-WAS" },
    { "name": "Yavatmal", "stateId": "MH", "code": "MH-YAV" },
    { "name": "Bishnupur", "stateId": "MN", "code": "MN-BIS" },
    { "name": "Chandel", "stateId": "MN", "code": "MN-CHA" },
    { "name": "Churachandpur", "stateId": "MN", "code": "MN-CHU" },
    { "name": "Imphal East", "stateId": "MN", "code": "MN-IME" },
    { "name": "Imphal West", "stateId": "MN", "code": "MN-IMW" },
    { "name": "Jiribam", "stateId": "MN", "code": "MN-JIR" },
    { "name": "Kakching", "stateId": "MN", "code": "MN-KAK" },
    { "name": "Kamjong", "stateId": "MN", "code": "MN-KAM" },
    { "name": "Kangpokpi", "stateId": "MN", "code": "MN-KAN" },
    { "name": "Noney", "stateId": "MN", "code": "MN-NON" },
    { "name": "Pherzawl", "stateId": "MN", "code": "MN-PHE" },
    { "name": "Senapati", "stateId": "MN", "code": "MN-SEN" },
    { "name": "Tamenglong", "stateId": "MN", "code": "MN-TAM" },
    { "name": "Tengnoupal", "stateId": "MN", "code": "MN-TEN" },
    { "name": "Thoubal", "stateId": "MN", "code": "MN-THO" },
    { "name": "Ukhrul", "stateId": "MN", "code": "MN-UKH" },
    { "name": "East Khasi Hills", "stateId": "ML", "code": "ML-EKH" },
    { "name": "East Jaintia Hills", "stateId": "ML", "code": "ML-EJH" },
    { "name": "West Jaintia Hills", "stateId": "ML", "code": "ML-WJH" },
    { "name": "West Khasi Hills", "stateId": "ML", "code": "ML-WKH" },
    { "name": "South West Khasi Hills", "stateId": "ML", "code": "ML-SWKH" },
    { "name": "East Garo Hills", "stateId": "ML", "code": "ML-EGH" },
    { "name": "West Garo Hills", "stateId": "ML", "code": "ML-WGH" },
    { "name": "South Garo Hills", "stateId": "ML", "code": "ML-SGH" },
    { "name": "South West Garo Hills", "stateId": "ML", "code": "ML-SWGH" },
    { "name": "North Garo Hills", "stateId": "ML", "code": "ML-NGH" },
    { "name": "Ri Bhoi", "stateId": "ML", "code": "ML-RB" },
    { "name": "Eastern West Khasi Hills", "stateId": "ML", "code": "ML-EWKH" },
    { "name": "Aizawl", "stateId": "MZ", "code": "MZ-AIZ" },
    { "name": "Champhai", "stateId": "MZ", "code": "MZ-CHA" },
    { "name": "Kolasib", "stateId": "MZ", "code": "MZ-KOL" },
    { "name": "Lawngtlai", "stateId": "MZ", "code": "MZ-LAW" },
    { "name": "Lunglei", "stateId": "MZ", "code": "MZ-LUN" },
    { "name": "Mamit", "stateId": "MZ", "code": "MZ-MAM" },
    { "name": "Saiha", "stateId": "MZ", "code": "MZ-SAI" },
    { "name": "Serchhip", "stateId": "MZ", "code": "MZ-SER" },
    { "name": "Hnahthial", "stateId": "MZ", "code": "MZ-HNA" },
    { "name": "Khawzawl", "stateId": "MZ", "code": "MZ-KHA" },
    { "name": "Saitual", "stateId": "MZ", "code": "MZ-SAT" },
    { "name": "Dimapur", "stateId": "NL", "code": "NL-DIM" },
    { "name": "Kiphire", "stateId": "NL", "code": "NL-KIP" },
    { "name": "Kohima", "stateId": "NL", "code": "NL-KOH" },
    { "name": "Longleng", "stateId": "NL", "code": "NL-LON" },
    { "name": "Mokokchung", "stateId": "NL", "code": "NL-MOK" },
    { "name": "Mon", "stateId": "NL", "code": "NL-MON" },
    { "name": "Peren", "stateId": "NL", "code": "NL-PER" },
    { "name": "Phek", "stateId": "NL", "code": "NL-PHE" },
    { "name": "Tuensang", "stateId": "NL", "code": "NL-TUE" },
    { "name": "Wokha", "stateId": "NL", "code": "NL-WOK" },
    { "name": "Zunheboto", "stateId": "NL", "code": "NL-ZUN" },
    { "name": "Noklak", "stateId": "NL", "code": "NL-NOK" },
    { "name": "Tseminyu", "stateId": "NL", "code": "NL-TSE" },
    { "name": "Niuland", "stateId": "NL", "code": "NL-NIU" },
    { "name": "Chumoukedima", "stateId": "NL", "code": "NL-CHU" },
    { "name": "Shamator", "stateId": "NL", "code": "NL-SHA" },
    { "name": "Angul", "stateId": "OD", "code": "OD-ANG" },
    { "name": "Balangir", "stateId": "OD", "code": "OD-BAL" },
    { "name": "Balasore", "stateId": "OD", "code": "OD-BLS" },
    { "name": "Bargarh", "stateId": "OD", "code": "OD-BAR" },
    { "name": "Bhadrak", "stateId": "OD", "code": "OD-BHA" },
    { "name": "Boudh", "stateId": "OD", "code": "OD-BOU" },
    { "name": "Cuttack", "stateId": "OD", "code": "OD-CUT" },
    { "name": "Deogarh", "stateId": "OD", "code": "OD-DEO" },
    { "name": "Dhenkanal", "stateId": "OD", "code": "OD-DHE" },
    { "name": "Gajapati", "stateId": "OD", "code": "OD-GAJ" },
    { "name": "Ganjam", "stateId": "OD", "code": "OD-GAN" },
    { "name": "Jagatsinghpur", "stateId": "OD", "code": "OD-JAG" },
    { "name": "Jajpur", "stateId": "OD", "code": "OD-JAJ" },
    { "name": "Jharsuguda", "stateId": "OD", "code": "OD-JHA" },
    { "name": "Kalahandi", "stateId": "OD", "code": "OD-KAL" },
    { "name": "Kandhamal", "stateId": "OD", "code": "OD-KAN" },
    { "name": "Kendrapara", "stateId": "OD", "code": "OD-KEN" },
    { "name": "Kendujhar", "stateId": "OD", "code": "OD-KEO" },
    { "name": "Khordha", "stateId": "OD", "code": "OD-KHO" },
    { "name": "Koraput", "stateId": "OD", "code": "OD-KOR" },
    { "name": "Malkangiri", "stateId": "OD", "code": "OD-MAL" },
    { "name": "Mayurbhanj", "stateId": "OD", "code": "OD-MAY" },
    { "name": "Nabarangpur", "stateId": "OD", "code": "OD-NAB" },
    { "name": "Nayagarh", "stateId": "OD", "code": "OD-NAY" },
    { "name": "Nuapada", "stateId": "OD", "code": "OD-NUA" },
    { "name": "Puri", "stateId": "OD", "code": "OD-PUR" },
    { "name": "Rayagada", "stateId": "OD", "code": "OD-RAY" },
    { "name": "Sambalpur", "stateId": "OD", "code": "OD-SAM" },
    { "name": "Subarnapur", "stateId": "OD", "code": "OD-SUB" },
    { "name": "Sundargarh", "stateId": "OD", "code": "OD-SUN" },
    { "name": "Amritsar", "stateId": "PB", "code": "PB-AMR" },
    { "name": "Barnala", "stateId": "PB", "code": "PB-BAR" },
    { "name": "Bathinda", "stateId": "PB", "code": "PB-BAT" },
    { "name": "Faridkot", "stateId": "PB", "code": "PB-FAR" },
    { "name": "Fatehgarh Sahib", "stateId": "PB", "code": "PB-FTG" },
    { "name": "Fazilka", "stateId": "PB", "code": "PB-FAZ" },
    { "name": "Ferozepur", "stateId": "PB", "code": "PB-FER" },
    { "name": "Gurdaspur", "stateId": "PB", "code": "PB-GUR" },
    { "name": "Hoshiarpur", "stateId": "PB", "code": "PB-HOS" },
    { "name": "Jalandhar", "stateId": "PB", "code": "PB-JAL" },
    { "name": "Kapurthala", "stateId": "PB", "code": "PB-KAP" },
    { "name": "Ludhiana", "stateId": "PB", "code": "PB-LUD" },
    { "name": "Mansa", "stateId": "PB", "code": "PB-MAN" },
    { "name": "Moga", "stateId": "PB", "code": "PB-MOG" },
    { "name": "Muktsar", "stateId": "PB", "code": "PB-MUK" },
    { "name": "Pathankot", "stateId": "PB", "code": "PB-PAT" },
    { "name": "Patiala", "stateId": "PB", "code": "PB-PAT" },
    { "name": "Rupnagar", "stateId": "PB", "code": "PB-RUP" },
    { "name": "Sahibzada Ajit Singh Nagar", "stateId": "PB", "code": "PB-SAS" },
    { "name": "Sangrur", "stateId": "PB", "code": "PB-SAN" },
    { "name": "Shahid Bhagat Singh Nagar", "stateId": "PB", "code": "PB-SBS" },
    { "name": "Tarn Taran", "stateId": "PB", "code": "PB-TAR" },
    { "name": "Malerkotla", "stateId": "PB", "code": "PB-MAL" },
    { "name": "Ajmer", "stateId": "RJ", "code": "RJ-AJM" },
    { "name": "Alwar", "stateId": "RJ", "code": "RJ-ALW" },
    { "name": "Banswara", "stateId": "RJ", "code": "RJ-BAN" },
    { "name": "Baran", "stateId": "RJ", "code": "RJ-BAR" },
    { "name": "Barmer", "stateId": "RJ", "code": "RJ-BRM" },
    { "name": "Bharatpur", "stateId": "RJ", "code": "RJ-BHA" },
    { "name": "Bhilwara", "stateId": "RJ", "code": "RJ-BHI" },
    { "name": "Bikaner", "stateId": "RJ", "code": "RJ-BIK" },
    { "name": "Bundi", "stateId": "RJ", "code": "RJ-BUN" },
    { "name": "Chittorgarh", "stateId": "RJ", "code": "RJ-CHI" },
    { "name": "Churu", "stateId": "RJ", "code": "RJ-CHU" },
    { "name": "Dausa", "stateId": "RJ", "code": "RJ-DAU" },
    { "name": "Dholpur", "stateId": "RJ", "code": "RJ-DHO" },
    { "name": "Dungarpur", "stateId": "RJ", "code": "RJ-DUN" },
    { "name": "Hanumangarh", "stateId": "RJ", "code": "RJ-HAN" },
    { "name": "Jaipur", "stateId": "RJ", "code": "RJ-JAI" },
    { "name": "Jaisalmer", "stateId": "RJ", "code": "RJ-JAS" },
    { "name": "Jalore", "stateId": "RJ", "code": "RJ-JAL" },
    { "name": "Jhalawar", "stateId": "RJ", "code": "RJ-JHA" },
    { "name": "Jhunjhunu", "stateId": "RJ", "code": "RJ-JHU" },
    { "name": "Jodhpur", "stateId": "RJ", "code": "RJ-JOD" },
    { "name": "Karauli", "stateId": "RJ", "code": "RJ-KAR" },
    { "name": "Kota", "stateId": "RJ", "code": "RJ-KOT" },
    { "name": "Nagaur", "stateId": "RJ", "code": "RJ-NAG" },
    { "name": "Pali", "stateId": "RJ", "code": "RJ-PAL" },
    { "name": "Pratapgarh", "stateId": "RJ", "code": "RJ-PRA" },
    { "name": "Rajsamand", "stateId": "RJ", "code": "RJ-RAJ" },
    { "name": "Sawai Madhopur", "stateId": "RJ", "code": "RJ-SAW" },
    { "name": "Sikar", "stateId": "RJ", "code": "RJ-SIK" },
    { "name": "Sirohi", "stateId": "RJ", "code": "RJ-SIR" },
    { "name": "Sri Ganganagar", "stateId": "RJ", "code": "RJ-SRI" },
    { "name": "Tonk", "stateId": "RJ", "code": "RJ-TON" },
    { "name": "Udaipur", "stateId": "RJ", "code": "RJ-UDA" },
    { "name": "East Sikkim", "stateId": "SK", "code": "SK-EAS" },
    { "name": "North Sikkim", "stateId": "SK", "code": "SK-NOR" },
    { "name": "South Sikkim", "stateId": "SK", "code": "SK-SOU" },
    { "name": "West Sikkim", "stateId": "SK", "code": "SK-WES" },
    { "name": "Pakyong", "stateId": "SK", "code": "SK-PAK" },
    { "name": "Soreng", "stateId": "SK", "code": "SK-SOR" },
    { "name": "Ariyalur", "stateId": "TN", "code": "TN-ARI" },
    { "name": "Chengalpattu", "stateId": "TN", "code": "TN-CHE" },
    { "name": "Chennai", "stateId": "TN", "code": "TN-CHN" },
    { "name": "Coimbatore", "stateId": "TN", "code": "TN-COI" },
    { "name": "Cuddalore", "stateId": "TN", "code": "TN-CUD" },
    { "name": "Dharmapuri", "stateId": "TN", "code": "TN-DHA" },
    { "name": "Dindigul", "stateId": "TN", "code": "TN-DIN" },
    { "name": "Erode", "stateId": "TN", "code": "TN-ERO" },
    { "name": "Kallakurichi", "stateId": "TN", "code": "TN-KAL" },
    { "name": "Kanchipuram", "stateId": "TN", "code": "TN-KAN" },
    { "name": "Kanyakumari", "stateId": "TN", "code": "TN-KAY" },
    { "name": "Karur", "stateId": "TN", "code": "TN-KAR" },
    { "name": "Krishnagiri", "stateId": "TN", "code": "TN-KRI" },
    { "name": "Madurai", "stateId": "TN", "code": "TN-MAD" },
    { "name": "Mayiladuthurai", "stateId": "TN", "code": "TN-MAY" },
    { "name": "Nagapattinam", "stateId": "TN", "code": "TN-NAG" },
    { "name": "Namakkal", "stateId": "TN", "code": "TN-NAM" },
    { "name": "Nilgiris", "stateId": "TN", "code": "TN-NIL" },
    { "name": "Perambalur", "stateId": "TN", "code": "TN-PER" },
    { "name": "Pudukkottai", "stateId": "TN", "code": "TN-PUD" },
    { "name": "Ramanathapuram", "stateId": "TN", "code": "TN-RAM" },
    { "name": "Ranipet", "stateId": "TN", "code": "TN-RAN" },
    { "name": "Salem", "stateId": "TN", "code": "TN-SAL" },
    { "name": "Sivaganga", "stateId": "TN", "code": "TN-SIV" },
    { "name": "Tenkasi", "stateId": "TN", "code": "TN-TEN" },
    { "name": "Thanjavur", "stateId": "TN", "code": "TN-THA" },
    { "name": "Theni", "stateId": "TN", "code": "TN-THE" },
    { "name": "Thoothukudi", "stateId": "TN", "code": "TN-THO" },
    { "name": "Tiruchirappalli", "stateId": "TN", "code": "TN-TIR" },
    { "name": "Tirunelveli", "stateId": "TN", "code": "TN-TIL" },
    { "name": "Tirupathur", "stateId": "TN", "code": "TN-TIP" },
    { "name": "Tiruppur", "stateId": "TN", "code": "TN-TPR" },
    { "name": "Tiruvallur", "stateId": "TN", "code": "TN-TRL" },
    { "name": "Tiruvannamalai", "stateId": "TN", "code": "TN-TRV" },
    { "name": "Tiruvarur", "stateId": "TN", "code": "TN-TRR" },
    { "name": "Vellore", "stateId": "TN", "code": "TN-VEL" },
    { "name": "Viluppuram", "stateId": "TN", "code": "TN-VIL" },
    { "name": "Virudhunagar", "stateId": "TN", "code": "TN-VIR" },
    { "name": "Adilabad", "stateId": "TG", "code": "TG-ADI" },
    { "name": "Bhadradri Kothagudem", "stateId": "TG", "code": "TG-BHA" },
    { "name": "Hyderabad", "stateId": "TG", "code": "TG-HYD" },
    { "name": "Jagtial", "stateId": "TG", "code": "TG-JAG" },
    { "name": "Jangaon", "stateId": "TG", "code": "TG-JAN" },
    { "name": "Jayashankar Bhupalpally", "stateId": "TG", "code": "TG-JAY" },
    { "name": "Jogulamba Gadwal", "stateId": "TG", "code": "TG-JOG" },
    { "name": "Kamareddy", "stateId": "TG", "code": "TG-KAM" },
    { "name": "Karimnagar", "stateId": "TG", "code": "TG-KAR" },
    { "name": "Khammam", "stateId": "TG", "code": "TG-KHA" },
    { "name": "Komaram Bheem Asifabad", "stateId": "TG", "code": "TG-KOM" },
    { "name": "Mahabubabad", "stateId": "TG", "code": "TG-MAH" },
    { "name": "Mahabubnagar", "stateId": "TG", "code": "TG-MBN" },
    { "name": "Mancherial", "stateId": "TG", "code": "TG-MAN" },
    { "name": "Medak", "stateId": "TG", "code": "TG-MED" },
    { "name": "Medchal-Malkajgiri", "stateId": "TG", "code": "TG-MEM" },
    { "name": "Mulugu", "stateId": "TG", "code": "TG-MUL" },
    { "name": "Nagarkurnool", "stateId": "TG", "code": "TG-NAG" },
    { "name": "Nalgonda", "stateId": "TG", "code": "TG-NAL" },
    { "name": "Narayanpet", "stateId": "TG", "code": "TG-NAR" },
    { "name": "Nirmal", "stateId": "TG", "code": "TG-NIR" },
    { "name": "Nizamabad", "stateId": "TG", "code": "TG-NIZ" },
    { "name": "Peddapalli", "stateId": "TG", "code": "TG-PED" },
    { "name": "Rajanna Sircilla", "stateId": "TG", "code": "TG-RAJ" },
    { "name": "Rangareddy", "stateId": "TG", "code": "TG-RAN" },
    { "name": "Sangareddy", "stateId": "TG", "code": "TG-SAN" },
    { "name": "Siddipet", "stateId": "TG", "code": "TG-SID" },
    { "name": "Suryapet", "stateId": "TG", "code": "TG-SUR" },
    { "name": "Vikarabad", "stateId": "TG", "code": "TG-VIK" },
    { "name": "Wanaparthy", "stateId": "TG", "code": "TG-WAN" },
    { "name": "Warangal", "stateId": "TG", "code": "TG-WAR" },
    { "name": "Yadadri Bhuvanagiri", "stateId": "TG", "code": "TG-YAD" },
    { "name": "Hanumakonda", "stateId": "TG", "code": "TG-HAN" },
    { "name": "Dhalai", "stateId": "TR", "code": "TR-DHA" },
    { "name": "Gomati", "stateId": "TR", "code": "TR-GOM" },
    { "name": "Khowai", "stateId": "TR", "code": "TR-KHO" },
    { "name": "North Tripura", "stateId": "TR", "code": "TR-NOR" },
    { "name": "Sepahijala", "stateId": "TR", "code": "TR-SEP" },
    { "name": "South Tripura", "stateId": "TR", "code": "TR-SOU" },
    { "name": "Unakoti", "stateId": "TR", "code": "TR-UNA" },
    { "name": "West Tripura", "stateId": "TR", "code": "TR-WES" },
    { "name": "Agra", "stateId": "UP", "code": "UP-AGR" },
    { "name": "Aligarh", "stateId": "UP", "code": "UP-ALI" },
    { "name": "Ambedkar Nagar", "stateId": "UP", "code": "UP-AMB" },
    { "name": "Amethi", "stateId": "UP", "code": "UP-AME" },
    { "name": "Amroha", "stateId": "UP", "code": "UP-AMR" },
    { "name": "Auraiya", "stateId": "UP", "code": "UP-AUR" },
    { "name": "Ayodhya", "stateId": "UP", "code": "UP-AYO" },
    { "name": "Azamgarh", "stateId": "UP", "code": "UP-AZA" },
    { "name": "Baghpat", "stateId": "UP", "code": "UP-BAG" },
    { "name": "Bahraich", "stateId": "UP", "code": "UP-BAH" },
    { "name": "Ballia", "stateId": "UP", "code": "UP-BAL" },
    { "name": "Balrampur", "stateId": "UP", "code": "UP-BAL" },
    { "name": "Banda", "stateId": "UP", "code": "UP-BAN" },
    { "name": "Barabanki", "stateId": "UP", "code": "UP-BAR" },
    { "name": "Bareilly", "stateId": "UP", "code": "UP-BAR" },
    { "name": "Basti", "stateId": "UP", "code": "UP-BAS" },
    { "name": "Bhadohi", "stateId": "UP", "code": "UP-BHA" },
    { "name": "Bijnor", "stateId": "UP", "code": "UP-BIJ" },
    { "name": "Budaun", "stateId": "UP", "code": "UP-BUD" },
    { "name": "Bulandshahr", "stateId": "UP", "code": "UP-BUL" },
    { "name": "Chandauli", "stateId": "UP", "code": "UP-CHA" },
    { "name": "Chitrakoot", "stateId": "UP", "code": "UP-CHI" },
    { "name": "Deoria", "stateId": "UP", "code": "UP-DEO" },
    { "name": "Etah", "stateId": "UP", "code": "UP-ETA" },
    { "name": "Etawah", "stateId": "UP", "code": "UP-ETW" },
    { "name": "Farrukhabad", "stateId": "UP", "code": "UP-FAR" },
    { "name": "Fatehpur", "stateId": "UP", "code": "UP-FAT" },
    { "name": "Firozabad", "stateId": "UP", "code": "UP-FIR" },
    { "name": "Gautam Buddha Nagar", "stateId": "UP", "code": "UP-GBN" },
    { "name": "Ghaziabad", "stateId": "UP", "code": "UP-GHA" },
    { "name": "Ghazipur", "stateId": "UP", "code": "UP-GHZ" },
    { "name": "Gonda", "stateId": "UP", "code": "UP-GON" },
    { "name": "Gorakhpur", "stateId": "UP", "code": "UP-GOR" },
    { "name": "Hamirpur", "stateId": "UP", "code": "UP-HAM" },
    { "name": "Hapur", "stateId": "UP", "code": "UP-HAP" },
    { "name": "Hardoi", "stateId": "UP", "code": "UP-HAR" },
    { "name": "Hathras", "stateId": "UP", "code": "UP-HAT" },
    { "name": "Jalaun", "stateId": "UP", "code": "UP-JAL" },
    { "name": "Jaunpur", "stateId": "UP", "code": "UP-JAU" },
    { "name": "Jhansi", "stateId": "UP", "code": "UP-JHA" },
    { "name": "Kannauj", "stateId": "UP", "code": "UP-KAN" },
    { "name": "Kanpur Dehat", "stateId": "UP", "code": "UP-KND" },
    { "name": "Kanpur Nagar", "stateId": "UP", "code": "UP-KNN" },
    { "name": "Kasganj", "stateId": "UP", "code": "UP-KAS" },
    { "name": "Kaushambi", "stateId": "UP", "code": "UP-KAU" },
    { "name": "Kheri", "stateId": "UP", "code": "UP-KHE" },
    { "name": "Kushinagar", "stateId": "UP", "code": "UP-KUS" },
    { "name": "Lalitpur", "stateId": "UP", "code": "UP-LAL" },
    { "name": "Lucknow", "stateId": "UP", "code": "UP-LUC" },
    { "name": "Maharajganj", "stateId": "UP", "code": "UP-MAH" },
    { "name": "Mahoba", "stateId": "UP", "code": "UP-MAO" },
    { "name": "Mainpuri", "stateId": "UP", "code": "UP-MAI" },
    { "name": "Mathura", "stateId": "UP", "code": "UP-MAT" },
    { "name": "Mau", "stateId": "UP", "code": "UP-MAU" },
    { "name": "Meerut", "stateId": "UP", "code": "UP-MEE" },
    { "name": "Mirzapur", "stateId": "UP", "code": "UP-MIR" },
    { "name": "Moradabad", "stateId": "UP", "code": "UP-MOR" },
    { "name": "Muzaffarnagar", "stateId": "UP", "code": "UP-MUZ" },
    { "name": "Pilibhit", "stateId": "UP", "code": "UP-PIL" },
    { "name": "Pratapgarh", "stateId": "UP", "code": "UP-PRA" },
    { "name": "Prayagraj", "stateId": "UP", "code": "UP-PRG" },
    { "name": "Raebareli", "stateId": "UP", "code": "UP-RAE" },
    { "name": "Rampur", "stateId": "UP", "code": "UP-RAM" },
    { "name": "Saharanpur", "stateId": "UP", "code": "UP-SAH" },
    { "name": "Sambhal", "stateId": "UP", "code": "UP-SAM" },
    { "name": "Sant Kabir Nagar", "stateId": "UP", "code": "UP-SKN" },
    { "name": "Shahjahanpur", "stateId": "UP", "code": "UP-SHA" },
    { "name": "Shamli", "stateId": "UP", "code": "UP-SHM" },
    { "name": "Shravasti", "stateId": "UP", "code": "UP-SHR" },
    { "name": "Siddharthnagar", "stateId": "UP", "code": "UP-SID" },
    { "name": "Sitapur", "stateId": "UP", "code": "UP-SIT" },
    { "name": "Sonbhadra", "stateId": "UP", "code": "UP-SON" },
    { "name": "Sultanpur", "stateId": "UP", "code": "UP-SUL" },
    { "name": "Unnao", "stateId": "UP", "code": "UP-UNN" },
    { "name": "Varanasi", "stateId": "UP", "code": "UP-VAR" },
    { "name": "Almora", "stateId": "UK", "code": "UK-ALM" },
    { "name": "Bageshwar", "stateId": "UK", "code": "UK-BAG" },
    { "name": "Chamoli", "stateId": "UK", "code": "UK-CHA" },
    { "name": "Champawat", "stateId": "UK", "code": "UK-CMP" },
    { "name": "Dehradun", "stateId": "UK", "code": "UK-DEH" },
    { "name": "Haridwar", "stateId": "UK", "code": "UK-HAR" },
    { "name": "Nainital", "stateId": "UK", "code": "UK-NAI" },
    { "name": "Pauri Garhwal", "stateId": "UK", "code": "UK-PAU" },
    { "name": "Pithoragarh", "stateId": "UK", "code": "UK-PIT" },
    { "name": "Rudraprayag", "stateId": "UK", "code": "UK-RUD" },
    { "name": "Tehri Garhwal", "stateId": "UK", "code": "UK-TEH" },
    { "name": "Udham Singh Nagar", "stateId": "UK", "code": "UK-UDH" },
    { "name": "Uttarkashi", "stateId": "UK", "code": "UK-UTT" },
    { "name": "Alipurduar", "stateId": "WB", "code": "WB-ALP" },
    { "name": "Bankura", "stateId": "WB", "code": "WB-BAN" },
    { "name": "Birbhum", "stateId": "WB", "code": "WB-BIR" },
    { "name": "Cooch Behar", "stateId": "WB", "code": "WB-COB" },
    { "name": "Dakshin Dinajpur", "stateId": "WB", "code": "WB-DAD" },
    { "name": "Darjeeling", "stateId": "WB", "code": "WB-DAR" },
    { "name": "Hooghly", "stateId": "WB", "code": "WB-HOO" },
    { "name": "Howrah", "stateId": "WB", "code": "WB-HOW" },
    { "name": "Jalpaiguri", "stateId": "WB", "code": "WB-JAL" },
    { "name": "Jhargram", "stateId": "WB", "code": "WB-JHA" },
    { "name": "Kalimpong", "stateId": "WB", "code": "WB-KAL" },
    { "name": "Kolkata", "stateId": "WB", "code": "WB-KOL" },
    { "name": "Malda", "stateId": "WB", "code": "WB-MAL" },
    { "name": "Murshidabad", "stateId": "WB", "code": "WB-MUR" },
    { "name": "Nadia", "stateId": "WB", "code": "WB-NAD" },
    { "name": "North 24 Parganas", "stateId": "WB", "code": "WB-N24" },
    { "name": "Paschim Bardhaman", "stateId": "WB", "code": "WB-PBD" },
    { "name": "Paschim Medinipur", "stateId": "WB", "code": "WB-PMD" },
    { "name": "Purba Bardhaman", "stateId": "WB", "code": "WB-PBN" },
    { "name": "Purba Medinipur", "stateId": "WB", "code": "WB-PMN" },
    { "name": "Purulia", "stateId": "WB", "code": "WB-PUR" },
    { "name": "South 24 Parganas", "stateId": "WB", "code": "WB-S24" },
    { "name": "Uttar Dinajpur", "stateId": "WB", "code": "WB-UTD" },
    { "name": "Nicobar", "stateId": "AN", "code": "AN-NIC" },
    { "name": "North and Middle Andaman", "stateId": "AN", "code": "AN-NMA" },
    { "name": "South Andaman", "stateId": "AN", "code": "AN-SAN" },
    { "name": "Chandigarh", "stateId": "CH", "code": "CH-CHA" },
    { "name": "Dadra and Nagar Haveli", "stateId": "DN", "code": "DN-DNH" },
    { "name": "Daman", "stateId": "DN", "code": "DN-DAM" },
    { "name": "Diu", "stateId": "DN", "code": "DN-DIU" },
    { "name": "Central Delhi", "stateId": "DL", "code": "DL-CEN" },
    { "name": "East Delhi", "stateId": "DL", "code": "DL-EAS" },
    { "name": "New Delhi", "stateId": "DL", "code": "DL-NEW" },
    { "name": "North Delhi", "stateId": "DL", "code": "DL-NOR" },
    { "name": "North East Delhi", "stateId": "DL", "code": "DL-NEA" },
    { "name": "North West Delhi", "stateId": "DL", "code": "DL-NWE" },
    { "name": "Shahdara", "stateId": "DL", "code": "DL-SHA" },
    { "name": "South Delhi", "stateId": "DL", "code": "DL-SOU" },
    { "name": "South East Delhi", "stateId": "DL", "code": "DL-SEA" },
    { "name": "South West Delhi", "stateId": "DL", "code": "DL-SWE" },
    { "name": "West Delhi", "stateId": "DL", "code": "DL-WES" },
    { "name": "Anantnag", "stateId": "JK", "code": "JK-ANA" },
    { "name": "Bandipora", "stateId": "JK", "code": "JK-BAN" },
    { "name": "Baramulla", "stateId": "JK", "code": "JK-BAR" },
    { "name": "Budgam", "stateId": "JK", "code": "JK-BUD" },
    { "name": "Doda", "stateId": "JK", "code": "JK-DOD" },
    { "name": "Ganderbal", "stateId": "JK", "code": "JK-GAN" },
    { "name": "Jammu", "stateId": "JK", "code": "JK-JAM" },
    { "name": "Kathua", "stateId": "JK", "code": "JK-KAT" },
    { "name": "Kishtwar", "stateId": "JK", "code": "JK-KIS" },
    { "name": "Kulgam", "stateId": "JK", "code": "JK-KUL" },
    { "name": "Kupwara", "stateId": "JK", "code": "JK-KUP" },
    { "name": "Poonch", "stateId": "JK", "code": "JK-POO" },
    { "name": "Pulwama", "stateId": "JK", "code": "JK-PUL" },
    { "name": "Rajouri", "stateId": "JK", "code": "JK-RAJ" },
    { "name": "Ramban", "stateId": "JK", "code": "JK-RAM" },
    { "name": "Reasi", "stateId": "JK", "code": "JK-REA" },
    { "name": "Samba", "stateId": "JK", "code": "JK-SAM" },
    { "name": "Shopian", "stateId": "JK", "code": "JK-SHO" },
    { "name": "Srinagar", "stateId": "JK", "code": "JK-SRI" },
    { "name": "Udhampur", "stateId": "JK", "code": "JK-UDH" },
    { "name": "Kargil", "stateId": "LA", "code": "LA-KAR" },
    { "name": "Leh", "stateId": "LA", "code": "LA-LEH" },
    { "name": "Lakshadweep", "stateId": "LD", "code": "LD-LAK" },
    { "name": "Karaikal", "stateId": "PY", "code": "PY-KAR" },
    { "name": "Mahe", "stateId": "PY", "code": "PY-MAH" },
    { "name": "Puducherry", "stateId": "PY", "code": "PY-PUD" },
    { "name": "Yanam", "stateId": "PY", "code": "PY-YAN" }
  ]

async function seedDatabase() {
  try {
    // Clear existing data (optional)
    await State.deleteMany({});
    await District.deleteMany({});
    console.log('Cleared existing states and districts');

    // Insert States
    const statesWithIds = statesData.map(state => ({
      _id: new mongoose.Types.ObjectId(),
      name: state.name,
      code: state.code
    }));

    const insertedStates = await State.insertMany(statesWithIds);
    console.log(`Inserted ${insertedStates.length} states`);

    // Create state code to ID mapping
    const stateCodeToIdMap = {};
    insertedStates.forEach(state => {
      stateCodeToIdMap[state.code] = state._id;
    });

    // Insert Districts
    const districtsWithIds = districtsData.map(district => ({
      _id: new mongoose.Types.ObjectId(),
      name: district.name,
      stateId: stateCodeToIdMap[district.stateId],
      code: district.code
    }));

    const insertedDistricts = await District.insertMany(districtsWithIds);
    console.log(`Inserted ${insertedDistricts.length} districts`);

    // Log sample data
    const sampleState = await State.findOne().lean();
    const sampleDistrict = await District.findOne().populate('stateId').lean();

    console.log('\nSample State:', JSON.stringify(sampleState, null, 2));
    console.log('\nSample District:', JSON.stringify(sampleDistrict, null, 2));

  } catch (error) {
    logger.error(`Database seeding error: ${error.message}`);
    console.error('Error seeding database:', error);
    throw error;
  }
}

// Function to be called from server.js or as a separate script
module.exports = { seedDatabase };